const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_POST_ADMIN: "GET_POST_ADMIN",
  GET_NEW_POSTS: "GET_NEW_POSTS",
  GET_POST_DETAIL: "GET_POST_DETAIL",
  EDIT_POST: "EDIT_POST",
  RESET_DATA_EDIT: "RESET_DATA_EDIT",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",
  GET_FEATURES: "GET_FEATURES",

  // USER
  GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
